<?php
$installer = $this;
$installer->startSetup();

$installer->run("
CREATE TABLE `{$this->getTable('emjainteractive_purchaseordermanagement/capture_payment')}` (
  `entity_id` int(10) unsigned NOT NULL auto_increment,
  `parent_id` int(10) unsigned NOT NULL,
  `base_shipping_captured` decimal(12,4) default NULL,
  `shipping_captured` decimal(12,4) default NULL,
  `amount_refunded` decimal(12,4) default NULL,
  `base_amount_paid` decimal(12,4) default NULL,
  `amount_canceled` decimal(12,4) default NULL,
  `base_amount_authorized` decimal(12,4) default NULL,
  `base_amount_paid_online` decimal(12,4) default NULL,
  `base_amount_refunded_online` decimal(12,4) default NULL,
  `base_shipping_amount` decimal(12,4) default NULL,
  `shipping_amount` decimal(12,4) default NULL,
  `amount_paid` decimal(12,4) default NULL,
  `amount_authorized` decimal(12,4) default NULL,
  `base_amount_ordered` decimal(12,4) default NULL,
  `base_shipping_refunded` decimal(12,4) default NULL,
  `shipping_refunded` decimal(12,4) default NULL,
  `base_amount_refunded` decimal(12,4) default NULL,
  `amount_ordered` decimal(12,4) default NULL,
  `base_amount_canceled` decimal(12,4) default NULL,
  `ideal_transaction_checked` tinyint(1) unsigned default NULL,
  `quote_payment_id` int(10) default NULL,
  `additional_data` text,
  `cc_exp_month` varchar(255) default NULL,
  `cc_ss_start_year` varchar(255) default NULL,
  `echeck_bank_name` varchar(255) default NULL,
  `method` varchar(255) default NULL,
  `cc_debug_request_body` varchar(255) default NULL,
  `cc_secure_verify` varchar(255) default NULL,
  `cybersource_token` varchar(255) default NULL,
  `ideal_issuer_title` varchar(255) default NULL,
  `protection_eligibility` varchar(255) default NULL,
  `cc_approval` varchar(255) default NULL,
  `cc_last4` varchar(255) default NULL,
  `cc_status_description` varchar(255) default NULL,
  `echeck_type` varchar(255) default NULL,
  `paybox_question_number` varchar(255) default NULL,
  `cc_debug_response_serialized` varchar(255) default NULL,
  `cc_ss_start_month` varchar(255) default NULL,
  `echeck_account_type` varchar(255) default NULL,
  `last_trans_id` varchar(255) default NULL,
  `cc_cid_status` varchar(255) default NULL,
  `cc_owner` varchar(255) default NULL,
  `cc_type` varchar(255) default NULL,
  `ideal_issuer_id` varchar(255) default NULL,
  `po_number` varchar(255) default NULL,
  `cc_exp_year` varchar(255) default NULL,
  `cc_status` varchar(255) default NULL,
  `echeck_routing_number` varchar(255) default NULL,
  `account_status` varchar(255) default NULL,
  `anet_trans_method` varchar(255) default NULL,
  `cc_debug_response_body` varchar(255) default NULL,
  `cc_ss_issue` varchar(255) default NULL,
  `echeck_account_name` varchar(255) default NULL,
  `cc_avs_status` varchar(255) default NULL,
  `cc_number_enc` varchar(255) default NULL,
  `cc_trans_id` varchar(255) default NULL,
  `flo2cash_account_id` varchar(255) default NULL,
  `paybox_request_number` varchar(255) default NULL,
  `address_status` varchar(255) default NULL,
  `additional_information` text,
  PRIMARY KEY  (`entity_id`),
  KEY `IDX_PARENT_ID` (`parent_id`),
  CONSTRAINT `FK_ORDER_CAPTURE_PAYMENT_PARENT` FOREIGN KEY (`parent_id`) REFERENCES `{$this->getTable('sales/order')}` (`entity_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
");
$installer->endSetup();