<div class="info-box">
    <div class="box-title">
        <h3><?php echo $this->__('PO Terms') ?></h3>
    </div>
    <div class="box-content">
        <p>
            <strong><?php echo $this->__('Net Terms') ?>:</strong> <?php echo $this->escapeHtml($this->getCustomer()->getNetTerms() ? $this->getCustomer()->getNetTerms() : Mage::getStoreConfig('payment/purchaseorder/default_net_terms')) ?><br />
            <strong><?php echo $this->__('PO Limit') ?>:</strong> <?php echo Mage::helper('core')->formatCurrency($this->getCustomer()->getPoLimit()) ?><br />
            <strong><?php echo $this->__('PO Credit (DUE)') ?>:</strong> <?php echo Mage::helper('core')->formatCurrency($this->getCustomer()->getPoCredit()) ?><br />
        </p>
    </div>
</div>